name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  HUSKY: 0

jobs:
  build:
    name: "Build test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build

  build-storybook:
    name: "Build storybook test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build:storybook

  type-check:
    name: "Type check"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run type-check
        run: pnpm run type-check

  eslint:
    name: "Check eslint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run eslint
        run: pnpm run eslint

  storybook-tests:
    name: "Run storybook tests"
    runs-on: ubuntu-24.04
    container:
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.56.1-noble
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run storybook tests
        run: pnpm run tests:storybook

  unit-tests:
    name: "Run unit tests"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: pnpm install
      - name: Run storybook tests
        run: pnpm run tests:unit
